# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FoodReal' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FoodReal
pod 'FirebaseAnalytics'
pod 'FirebaseFirestore'
pod 'FirebaseFirestoreSwift'
pod 'FirebaseAuth' 
pod 'LBTATools', '~> 1.0'


end
